# Generated by Django 5.1.2 on 2024-11-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_prod', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('disponible', models.CharField(max_length=10)),
            ],
        ),
    ]
