# Generated by Django 5.1.2 on 2024-12-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id_empresa', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_sucursal', models.PositiveSmallIntegerField()),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('ubicacion_empresa', models.CharField(max_length=50)),
            ],
        ),
    ]
